# Generated by Django 2.2.5 on 2019-10-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('money', models.CharField(max_length=20)),
                ('first_time', models.DateField()),
                ('number', models.CharField(max_length=20)),
            ],
        ),
    ]
